version: 2
updates:

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 99
  reviewers:
  - credfeto
  assignees:
  - credfeto
  commit-message:
    prefix: "[Dependencies]"
  labels:
  - "nuget"
  - "dependencies"
  - "Changelog Not Required"
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: "AspNetCoreRateLimit"
  - dependency-name: "AsyncFixer"
  - dependency-name: "AutoBogus.NSubstitute"
  - dependency-name: "AWSSDK.*"
  - dependency-name: "BenchmarkDotNet"
  - dependency-name: "BenchmarkDotNet.Diagnostics.dotTrace"
  - dependency-name: "BinaryToText"
  - dependency-name: "Bogus"
  - dependency-name: "Castle.Core"
  - dependency-name: "Cocona"
  - dependency-name: "codecracker.CSharp"
  - dependency-name: "CommandLineParser"
  - dependency-name: "CountryData.Bogus"
  - dependency-name: "coverlet.*"
  - dependency-name: "Credfeto.ChangeLog.*"
  - dependency-name: "Credfeto.Database.*"
  - dependency-name: "Credfeto.Date.*"
  - dependency-name: "Credfeto.Docker.HealthCheck.Http.Client"
  - dependency-name: "Credfeto.Enumeration.*"
  - dependency-name: "Credfeto.Extensions.Configuration.Typed.Json"
  - dependency-name: "Credfeto.Extensions.Linq"
  - dependency-name: "Credfeto.ImageLoader"
  - dependency-name: "Credfeto.Package.*"
  - dependency-name: "Credfeto.Random"
  - dependency-name: "Credfeto.Services.Startup.*"
  - dependency-name: "Credfeto.Version.Information.Generator"
  - dependency-name: "Cryptography.ECDSA.Secp256K1"
  - dependency-name: "CSharpier.MSBuild"
  - dependency-name: "CSharpIsNullAnalyzer.*"
  - dependency-name: "Dapper"
  - dependency-name: "DisableDateTimeNow"
  - dependency-name: "Discord.Net"
  - dependency-name: "Discord.Net.Analyzers"
  - dependency-name: "dotnetstandard-bip39"
  - dependency-name: "Evo.Keccak"
  - dependency-name: "FluentValidation.*"
  - dependency-name: "FunFair.Authentication.*"
  - dependency-name: "FunFair.Balance.Bot.Client"
  - dependency-name: "FunFair.BuildCheck.*"
  - dependency-name: "FunFair.BuildVersion.*"
  - dependency-name: "FunFair.Client.*"
  - dependency-name: "FunFair.CodeAnalysis"
  - dependency-name: "FunFair.Common.*"
  - dependency-name: "FunFair.Content.Package.Management.*"
  - dependency-name: "FunFair.Ethereum.*"
  - dependency-name: "FunFair.Geo.Logic"
  - dependency-name: "FunFair.Random"
  - dependency-name: "FunFair.RateLimit"
  - dependency-name: "FunFair.Server.Ethereum.Accounts.*"
  - dependency-name: "FunFair.ServerMonitoring.*"
  - dependency-name: "FunFair.SignalR.*"
  - dependency-name: "FunFair.SinglePayout.*"
  - dependency-name: "FunFair.Swagger.*"
  - dependency-name: "FunFair.Test.Common"
  - dependency-name: "HexMate"
  - dependency-name: "HtmlAgilityPack"
  - dependency-name: "IPAddressRange"
  - dependency-name: "Jetbrains.Annotations"
  - dependency-name: "Keccak256"
  - dependency-name: "LibGit2Sharp"
  - dependency-name: "LibSassHost.*"
  - dependency-name: "Magick.NET-Q16-AnyCPU"
  - dependency-name: "MaxMind.GeoIP2"
  - dependency-name: "MaxMind.MinFraud"
  - dependency-name: "Mediator.*"
  - dependency-name: "MediatR.*"
  - dependency-name: "Meziantou.Analyzer"
  - dependency-name: "Meziantou.Extensions.Logging.Xunit.*"
  - dependency-name: "Meziantou.Framework.InlineSnapshotTesting"
  - dependency-name: "Meziantou.Xunit.ParallelTestFramework"
  - dependency-name: "Microsoft.ApplicationInsights.AspNetCore"
  - dependency-name: "Microsoft.AspNetCore.SignalR.StackExchangeRedis"
  - dependency-name: "Microsoft.CodeAnalysis.Analyzers"
  - dependency-name: "Microsoft.CodeAnalysis.CSharp.*"
  - dependency-name: "Microsoft.Data.SqlClient"
  - dependency-name: "Microsoft.Extensions.*"
  - dependency-name: "Microsoft.IO.RecyclableMemoryStream.*"
  - dependency-name: "Microsoft.NET.Test.Sdk"
  - dependency-name: "Microsoft.Sbom.Targets.*"
  - dependency-name: "Microsoft.Testing.Extensions.CodeCoverage"
  - dependency-name: "Microsoft.Toolkit.HighPerformance"
  - dependency-name: "Microsoft.VisualStudio.Threading"
  - dependency-name: "Microsoft.VisualStudio.Threading.Analyzers"
  - dependency-name: "MSBuild.Sdk.SqlProj"
  - dependency-name: "NBitcoin"
  - dependency-name: "Nethereum.*"
  - dependency-name: "Newtonsoft.Json"
  - dependency-name: "Nito.AsyncEx.Coordination"
  - dependency-name: "NonBlocking"
  - dependency-name: "Npgsql"
  - dependency-name: "NSubstitute"
  - dependency-name: "NSubstitute.Analyzers.CSharp"
  - dependency-name: "NuGet.*"
  - dependency-name: "Nullable.Extended.Analyzer"
  - dependency-name: "NWebsec.AspNetCore.Middleware.*"
  - dependency-name: "Octopus.Client"
  - dependency-name: "OxyPlot.*"
  - dependency-name: "Philips.CodeAnalysis.DuplicateCodeAnalyzer"
  - dependency-name: "Philips.CodeAnalysis.MaintainabilityAnalyzers"
  - dependency-name: "Polly"
  - dependency-name: "Portable.BouncyCastle"
  - dependency-name: "QRCoder"
  - dependency-name: "Roslynator.Analyzers"
  - dependency-name: "ScottPlot"
  - dependency-name: "Secp256k1.Native"
  - dependency-name: "SecurityCodeScan.VS2019"
  - dependency-name: "Sendgrid"
  - dependency-name: "Serilog"
  - dependency-name: "Serilog.Enrichers.AssemblyName"
  - dependency-name: "Serilog.Enrichers.Demystifier"
  - dependency-name: "Serilog.Enrichers.Environment"
  - dependency-name: "Serilog.Enrichers.Process"
  - dependency-name: "Serilog.Enrichers.Sensitive"
  - dependency-name: "Serilog.Enrichers.Thread"
  - dependency-name: "Serilog.Exceptions"
  - dependency-name: "Serilog.Extensions.Logging"
  - dependency-name: "Serilog.Sinks.Console"
  - dependency-name: "Serilog.Sinks.Debug"
  - dependency-name: "Serilog.Sinks.Loggly"
  - dependency-name: "Serilog.Sinks.Xunit"
  - dependency-name: "SHA3"
  - dependency-name: "SixLabors.ImageSharp.*"
  - dependency-name: "SmartAnalyzers.CSharpExtensions.Annotations"
  - dependency-name: "SonarAnalyzer.CSharp"
  - dependency-name: "SourceLink.Create.CommandLine"
  - dependency-name: "StronglyTypedId"
  - dependency-name: "Swashbuckle.*"
  - dependency-name: "System.Data.SqlClient"
  - dependency-name: "System.IdentityModel.Tokens.Jwt"
  - dependency-name: "System.Interactive.Async"
  - dependency-name: "System.IO.*"
  - dependency-name: "System.Reactive"
  - dependency-name: "System.Runtime.*"
  - dependency-name: "System.Text.*"
  - dependency-name: "System.Threading.Tasks.*"
  - dependency-name: "TeamCity.VSTest.TestAdapter"
  - dependency-name: "ThisAssembly.AssemblyInfo"
  - dependency-name: "ToStringWithoutOverrideAnalyzer"
  - dependency-name: "TwitchLib.*"
  - dependency-name: "UAParser"
  - dependency-name: "xunit"
  - dependency-name: "xunit.analyzers"
  - dependency-name: "xunit.runner.visualstudio"
  - dependency-name: "xunit.v3.*"