name: "Dependabot: Approve updates"
on:
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests
  # could and should work, at least for public repos;
  # tracking issue for this action's issue:
  # https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

permissions:
  contents: read

jobs:
  enable-auto-merge-github-actions:
    if: |-
      vars.DEPENDABOT_AUTOMERGE == 'true' &&
      startsWith(github.head_ref, 'dependabot/github_actions/')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.

    steps:

    - name: "Initialise Workspace"
      if: startsWith(runner.name, 'buildagent-')
      shell: bash
      run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

    - name: "Check Repo Owner"
      uses: actions/github-script@v7.0.1
      with:
        script: |
          core.info('Owner: ${{github.repository_owner}}');

    - name: "Auto Merge"
      uses: alexwilson/enable-github-automerge-action@2.0.0
      with:
        github-token: ${{secrets.SOURCE_PUSH_TOKEN}}
        merge-method: "MERGE"

  enable-auto-merge-npm:
    if: |-
      vars.DEPENDABOT_AUTOMERGE == 'true' &&
      startsWith(github.head_ref, 'dependabot/npm_and_yarn/')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.

    steps:
      - name: "Initialise Workspace"
        if: startsWith(runner.name, 'buildagent-')
        shell: bash
        run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

      - name: "Check Repo Owner"
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.info('Owner: ${{github.repository_owner}}');

      - name: "Auto Merge"
        uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: ${{secrets.SOURCE_PUSH_TOKEN}}
          merge-method: "MERGE"

  auto-approve-dependabot-gitub-actions:
    if: |-
      vars.DEPENDABOT_AUTOMERGE == 'true' &&
      startsWith(github.head_ref, 'dependabot/github_actions/')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: "Initialise Workspace"
      if: startsWith(runner.name, 'buildagent-')
      shell: bash
      run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

    - name: "Check Repo Owner"
      uses: actions/github-script@v7.0.1
      with:
        script: |
          core.info('Owner: ${{github.repository_owner}}');

    - name: "Approve"
      uses: hmarr/auto-approve-action@v4
      with:
        github-token: ${{secrets.SOURCE_PUSH_TOKEN}}

  auto-approve-dependabot-npm:
    if: |-
      vars.DEPENDABOT_AUTOMERGE == 'true' &&
      startsWith(github.head_ref, 'dependabot/npm_and_yarn/')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Initialise Workspace"
        if: startsWith(runner.name, 'buildagent-')
        shell: bash
        run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

      - name: "Check Repo Owner"
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.info('Owner: ${{github.repository_owner}}');

      - name: "Approve"
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{secrets.SOURCE_PUSH_TOKEN}}
