name: rebase pull requests
on:
  push:
    branches:
      - main
  release:
    types: [published]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event == 'release'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: bbeesley/gha-auto-dependabot-rebase@v1.3.48
        env:
          GITHUB_TOKEN: ${{secrets.SOURCE_PUSH_TOKEN}}
