name: "PR: Update"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false

env:
  HEAD_REF: ${{github.head_ref}}
  BASE_REF: ${{github.base_ref}}

jobs:
  info:
    if: endsWith(github.repository , '-template')
    runs-on: ubuntu-latest
    steps:
      - name: "Initialise Workspace"
        if: startsWith(runner.name, 'buildagent-')
        shell: bash
        run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

      - name: "Set Active Environment"
        shell: bash
        run: |
          {
          echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
          echo "ACTIVE_HOSTNAME=$HOSTNAME"
          echo "ACTIVE_USER=$USER"
          } >> "$GITHUB_ENV"

      - name: "Info"
        uses: actions/github-script@v7.0.1
        with:
          script: |
            core.info('Branch: ${{env.HEAD_REF}}');
            core.info('Base Branch: ${{env.BASE_REF}}');
            core.info('Repo: ${{github.repository}}');
            core.info('Owner: ${{github.repository_owner}}');
            core.info('Assigned: ${{github.event.pull_request.assignee.login}}');
            core.info('Assigned: ${{github.event.pull_request.assignees[0].login}}');
            core.info('Last Modified By: ${{github.event.pull_request.head.user.login}}');
            core.info('PR Creator: ${{github.event.pull_request.creator.login}}');
            core.info('PR Owner: ${{github.event.pull_request.owner}}');
            core.info('Actor: ${{github.actor}}');

  add-pr-label:
    if: ${{github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    steps:
      - name: "Initialise Workspace"
        if: startsWith(runner.name, 'buildagent-')
        shell: bash
        run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

      - name: "Set Active Environment"
        shell: bash
        run: |
          {
          echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
          echo "ACTIVE_HOSTNAME=$HOSTNAME"
          echo "ACTIVE_USER=$USER"
          } >> "$GITHUB_ENV"

      - name: "Add Labels"
        uses: actions/labeler@v6
        with:
          repo-token: ${{secrets.SOURCE_PUSH_TOKEN}}
          configuration-path: .github/labeler.yml
          sync-labels: true

  assign-to-creator:
    if: |-
      ${{!github.event.pull_request.assignee.login
      && github.event_name == 'pull_request'
      && ( github.event.action == 'opened' || github.event.action == 'reopened')
      && github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    steps:
      - name: "Initialise Workspace"
        if: startsWith(runner.name, 'buildagent-')
        shell: bash
        run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

      - name: "Set Active Environment"
        shell: bash
        run: |
          {
          echo "ACTIVE_RUNNER_NAME=${{runner.name}}"
          echo "ACTIVE_HOSTNAME=$HOSTNAME"
          echo "ACTIVE_USER=$USER"
          } >> "$GITHUB_ENV"

      - name: "Assign PR to the creator"
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        with:
          repo-token: ${{secrets.SOURCE_PUSH_TOKEN}}
