--- # Reformatting MSSQL
name: "Standardise: MSSQL Format"

on:
  push:
    branches-ignore:
      - "release/*"
      - "hotfix/*"
    paths:
      - '**.sql'
      - '.github/workflows/reformat-sql.yml'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  standardise-tsql-files:

    if: |-
        github.event.pull_request.draft == false
        && ( !startsWith(github.head_ref, 'release/')
        && !startsWith(github.head_ref, 'hotfix/') )
        && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: "Initialise Workspace"
        if: startsWith(runner.name, 'buildagent-')
        shell: bash
        run: sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"

      - name: "Checkout Source"
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{secrets.SOURCE_PUSH_TOKEN}}

      - name: "Reformat"
        uses: credfeto/action-sql-format@v1.5.1

      - name: "Commit Changes"
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "[Reformat] SQL Files to common format"
          file_pattern: "*.sql"
          commit_user_name: "fun-sqlfmt[bot]"
          commit_user_email: "credfeto@users.noreply.github.com"
          commit_author: "fun-sqlfmt[bot] <credfeto@users.noreply.github.com>"
          skip_dirty_check: false
